# Generated by Django 4.1.4 on 2023-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Province no 1', 'Province No 1'), ('Madhesh', 'Madhesh '), ('Bagmati', 'Bagmati '), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpaschim', 'Sudurpashchim')], max_length=100),
        ),
    ]
