# Generated by Django 4.1.4 on 2023-04-10 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('pidx', models.CharField(max_length=100)),
                ('paymentstatus', models.CharField(max_length=100)),
                ('txnid', models.CharField(max_length=100)),
                ('paid', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='paymentstatus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.khaltipayment'),
        ),
    ]
