# Generated by Django 4.1.4 on 2023-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_khaltipayment_remove_orderplaced_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khaltipayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='khaltipayment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='khaltipayment',
            name='paymentstatus',
        ),
        migrations.RemoveField(
            model_name='khaltipayment',
            name='txnid',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='paidamount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='pidx',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='txnid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='paymentstatus',
            field=models.CharField(max_length=100),
        ),
    ]
