# Generated by Django 4.1.4 on 2023-04-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_khaltipayment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='paidamount',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='pidx',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='txnid',
        ),
        migrations.AddField(
            model_name='khaltipayment',
            name='paidamount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='khaltipayment',
            name='paymentstatus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='khaltipayment',
            name='txnid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='paymentstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khaltipayment'),
        ),
    ]
