# Generated by Django 4.1.4 on 2023-04-13 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_orderplaced_paidamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khalti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(max_length=100)),
                ('paymentstatus', models.CharField(default='', max_length=100)),
                ('txnid', models.CharField(default='', max_length=100)),
                ('paidamount', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='paymentstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khalti'),
        ),
        migrations.DeleteModel(
            name='KhaltiPayment',
        ),
    ]
