# Generated by Django 4.1.4 on 2023-04-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_khalti_alter_orderplaced_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='paymentstatus',
            field=models.CharField(default='', max_length=50),
        ),
    ]
